apiVersion: v1
kind: Service
metadata:
  name: medflow-frontend-service
spec:
  selector:
    app: medflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medflow-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medflow-frontend
  template:
    metadata:
      labels:
        app: medflow-frontend
    spec:
      containers:
      - name: medflow-frontend
        image: medflow-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
